apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: pensionapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app: frontend